### ISSUE TITLE
Does not work on Chromium

### ISSUE THREAD

**Issue by Architector4** [gargakshit/heavy.js#1]
The demo page is too fast and light when using Chromium. Console shows the following error:

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at injectStyles (heavy.js:9:19)
    at makeHeavy (heavy.js:76:3)
    at heavy.js:82:1
```

Chromium version 102.0.5005.61

**Comment by gargakshit** [comment]
Fixed in fa84886309cfe2cbe603872e9e68f5ccfb371c46
